---
title: "SAS Data Exploration "
author: "Murera Gisa"
date: "`r Sys.Date()`"
output: 
  rmdformats::material: 
    self_contained: true
    thumbnails: true
    lightbox: true
    gallery: true
    highlight: espresso
toc: yes
toc_depth: 3
editor_options: 
  chunk_output_type: console
---
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
# Loading Libraries
library(explore)
library(DT)
library(data.table)
library(RColorBrewer)
library(rmarkdown)
library(knitr)
library(parallel)
library(DataExplorer)
library(data.table)
library(tidyverse)
library(networkD3)
theme_set(theme_bw())

opts_chunk$set(
collapse = TRUE,
fig.width = 6,
fig.height = 6,
fig.align = "center",
warning = FALSE,
message = FALSE,
screenshot.force = FALSE
)

cropyield <- fread(here::here("data/Crop_Yield_data.csv"))
weather <- fread(here::here("data/meteo_data.csv"))

data_list <- list(cropyield, weather)
tbl <- data_list %>% reduce(inner_join, by=c("year","Districts","Seasons"))
#plot_str(data_list)
```

Quickly visualize the structure of all the data

```{r}
diagonalNetwork(
  plot_str(data_list, print_network = TRUE),
  width = 800,
  height = 800,
  fontSize = 20,
  margin = list(
    "left" = 50,
    "right" = 50
  )
)
```

You may also try `plot_str(data_list, type = "r")` for a radial network.

# Data Source and Description

https://allisonhorst.github.io/palmerpenguins/articles/intro.html
https://cran.r-project.org/web/packages/explore/vignettes/explore_penguins.html
# Data Source


```{r, message=FALSE, warning=FALSE}
glimpse(cropyield)

#Describing the data
cropyield %>% describe() %>% DT::datatable()

colSums(is.na(cropyield))
visdat::vis_dat(
  cropyield)
visdat::vis_miss(cropyield, cluster = T)

```

# Exploration of crops and seasons

```{r}
# Count penguins for each species / sex
cropyield %>%
  count(year, Seasons, Crop_Type, .drop = FALSE)
```



```{r}
cropyield %>% ggplot(.,aes(x = Crop_Type , fill = Seasons)) +
  geom_bar(alpha = 0.8) +scale_color_brewer(palette="Set3") +
  theme_minimal() +
  facet_wrap(~year, ncol = 3) +
  coord_flip()
```

We have 27 different distinct crop types but with some repetitions of some crops.

```{r}
cropyield %>%  ggplot(., aes(x = log(Production), y = Seasons, color = Seasons )) + geom_boxplot() +
  geom_jitter(alpha =0.3)
```


# Data Tables

```{r}
cropyield %>% DT::datatable()
weather %>% DT::datatable()

```

```{r}



```

